name: build
on: [push, pull_request]
jobs:
  compile:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: graphviz
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r requirements.txt
      - run: make
      - name: Upload Images
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/*.png
